# Generated by Django 4.0.3 on 2023-07-20 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hat',
            name='wardrobe_location',
        ),
        migrations.AddField(
            model_name='binvo',
            name='import_href',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hat',
            name='bin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hats_rest.binvo'),
            preserve_default=False,
        ),
    ]
