# Generated by Django 4.0.3 on 2023-07-20 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0002_remove_hat_wardrobe_location_binvo_import_href_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BinVO',
            new_name='LocationVO',
        ),
        migrations.RemoveField(
            model_name='hat',
            name='bin',
        ),
        migrations.AddField(
            model_name='hat',
            name='wardrobe_location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='hat', to='hats_rest.locationvo'),
            preserve_default=False,
        ),
    ]
