# Generated by Django 4.0.3 on 2023-07-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0003_rename_binvo_locationvo_remove_hat_bin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationvo',
            old_name='bin_number',
            new_name='section_number',
        ),
        migrations.RenameField(
            model_name='locationvo',
            old_name='bin_size',
            new_name='shelf_number',
        ),
    ]
